---
title: "Flight Cancellation Modelling"
author: "Albert Cao"
date: "12/9/2020"
output: 
  prettydoc::html_pretty:
    theme: Architect
    highlight: github
    toc: true
    toc_depth: 2
---

Kaggle site: https://www.kaggle.com/c/flights-status

## 1. Reading Datasets and Loading Libraries 

```{r}
library(stringi)
library(dplyr)
library(randomForest)
library(ggplot2)
library(ggthemes)
```

```{r}
flight.training<- read.csv("flight.training.csv")
flight.testing<- read.csv("flight.testing.csv")
airport.info<- read.csv("training.airport.info.csv")
delay.date<- read.csv("delay.date.csv")
cancel.date<- read.csv("cancel.date.csv")
delay.airport<- read.csv("delay.csv")
```

## 2. Data Cleaning and Variable Transformation 

### Original Training and Testing Datasets
```{r}
#Cleaning Destnation City Airport Names
flight.training$d.state<- stri_sub(flight.training$Destination_city, -2,-1)
flight.testing$d.state<- stri_sub(flight.testing$Destination_city, -2,-1)
biggest<- c("DEN","DFW","IAD","MCO","IAH","SLC","ORD","SFO","JFK","DTW")

# Identifying the top 10 Busiest Aiports in the U.S.
flight.training$biggest2<- ifelse(flight.training$Origin_airport %in% biggest, 1,0)
flight.testing$biggest2<- ifelse(flight.testing$Origin_airport %in% biggest, 1,0)
```

### Airport Information Dataset
```{r}
airport.info<- airport.info[,-1]
colnames(airport.info)<- c("Origin_airport", "Departure", "Arrival", "Total.Ops", "Departure.Seats", "Ave.Dep.Seats", "Arrival.Seats", "Ave.Arr.Seats")
airport.info<- airport.info[c(-1:-5, -239),]
airport.info$Origin_airport<- stri_sub(airport.info$Origin_airport, 1, 3)
for(i in 2:8){
  airport.info[,i]<- as.numeric(airport.info[,i])
}
flight.training<- left_join(flight.training, airport.info, "Origin_airport")
flight.testing<- left_join(flight.testing, airport.info, "Origin_airport")
flight.training$tot<- flight.training$Arrival.Seats+flight.training$Departure.Seats
flight.testing$tot<- flight.testing$Arrival.Seats+flight.testing$Departure.Seats
flight.training$to<- flight.training$Arrival.Seats+flight.training$Departure.Seats
flight.testing$to<- flight.testing$Arrival.Seats+flight.testing$Departure.Seats
```

### Delay and Cancellation Datasets

```{r}
flight.training$Date<- paste(flight.training$MONTH, flight.training$DAY)
flight.training$Date<- gsub("[[:space:]]","",flight.training$Date)
delay.date<- delay.date[-91:-95,]
delay.date$Date<- gsub("/","\\",delay.date$Date)
flight.training<- left_join(flight.training, delay.date, "Date")
flight.testing$Date<- paste(flight.testing$MONTH, flight.testing$DAY)
flight.testing$Date<- gsub("[[:space:]]","",flight.testing$Date)
flight.testing<- left_join(flight.testing, delay.date, "Date")

cancel.date$Date<- gsub("/","\\",cancel.date$Date)
flight.training<- left_join(flight.training, cancel.date, "Date")
flight.testing<- left_join(flight.testing, cancel.date, "Date")

delay.airport<- delay.airport[,c(1,7)]
names(delay.airport)<- c("Destination_airport", "arrival.delay")
flight.training<- left_join(flight.training, delay.airport, "Destination_airport")
flight.testing<- left_join(flight.testing, delay.airport, "Destination_airport")
```

## 3. Model Construction and Testing

```{r}
set.seed(1234)
indi3<- sample(nrow(flight.training), nrow(flight.training)*0.7, replace = F)
tr2<- flight.training[indi3,]
te2<- flight.training[-indi3,]

# Best Model Accuracy: 0.99841 Time Elapsed: 175.369s - CPU: 3 GHz Intel Core i5
flight.m2<- randomForest(data=flight.training, as.factor(Cancelled)~ Destination_airport + SCHEDULED_DEPARTURE + biggest2 +DAY + O.City + Distance + DAY_OF_WEEK +MONTH + Org_airport_long+ FLIGHT_NUMBER + SCHEDULED_TIME + SCHEDULED_ARRIVAL + tot +X..Delayed+precent+cancellation+arrival.delay ,mtry=5,ntree=500,importance=TRUE)

flight.m3<- randomForest(data=tr2, as.factor(Cancelled)~ Destination_airport + SCHEDULED_DEPARTURE + biggest2 +DAY + O.City + Distance + DAY_OF_WEEK +MONTH + Org_airport_long+ FLIGHT_NUMBER + SCHEDULED_TIME + SCHEDULED_ARRIVAL + tot +X..Delayed+precent+cancellation+arrival.delay ,mtry=5,ntree=500,importance=TRUE)
system.time(randomForest(data=flight.training, as.factor(Cancelled)~ Destination_airport + SCHEDULED_DEPARTURE + biggest2 +DAY + O.City + Distance + DAY_OF_WEEK +MONTH + Org_airport_long+ FLIGHT_NUMBER + SCHEDULED_TIME + SCHEDULED_ARRIVAL + tot +X..Delayed+precent+cancellation+arrival.delay ,mtry=5,ntree=500,importance=TRUE))
# Most Efficient Model Accuracy: 0.99557 Time Elapsed: 1.754s - CPU: 3 GHz Intel Core i5
flight.efficient<- randomForest(data=tr2, as.factor(Cancelled)~ Destination_airport + SCHEDULED_DEPARTURE +DAY + O.City + Distance + DAY_OF_WEEK +MONTH + Org_airport_long+ FLIGHT_NUMBER + SCHEDULED_TIME + SCHEDULED_ARRIVAL ,mtry=4,ntree=10,importance=TRUE)
system.time(randomForest(data=tr2, as.factor(Cancelled)~ Destination_airport + SCHEDULED_DEPARTURE +DAY + O.City + Distance + DAY_OF_WEEK +MONTH + Org_airport_long+ FLIGHT_NUMBER + SCHEDULED_TIME + SCHEDULED_ARRIVAL ,mtry=4,ntree=10,importance=TRUE))

# Testing Accuracy 
p2<- predict(flight.m3, newdata = te2, type = "response")
pred2<- p2 == "YES"
cc<- te2$Cancelled
t1<-table(pred2, cc)
(t1[1,1]+t1[2,2])/sum(t1)
```

```{r}
p3<- predict(flight.m2, newdata = flight.testing, type = "response")
pred3<- p3 == "YES"
pred3<- as.data.frame(pred3)
pred3$Ob<- rownames(pred3)
pred3[,3]<- pred3[,1]
pred3[,1]<- pred3[,2]
pred3[,2]<- pred3[,3]
pred3<- pred3[,-3]
pred3[,2]<- gsub(FALSE, "NO", pred3[,2])
pred3[,2]<- gsub(TRUE, "YES", pred3[,2])
colnames(pred3)<- c("Ob", "Cancelled")
write.csv(pred3, "flight.pred.csv", row.names = FALSE)
```


## 4. Supporting Visualizations

```{r}
tt<- as.data.frame(prop.table(table(flight.training$Cancelled, flight.training$to)))
tt<- tt[seq(2, nrow(tt),2),]
tt$Var2<-as.numeric(as.character(tt$Var2))
ggplot(tt, aes(x=as.numeric(Var2), y=Freq))+
  geom_point()+
  theme_classic()+
  ggtitle("Flight Cancellation Rate vs. Passenger Traffic")+
  xlab("Passenger Traffic")+
  ylab("Flight Cancellation Rate")

aa<- numeric(0)
for(i in 1:20){
flight.efficient<- randomForest(data=tr2, as.factor(Cancelled)~ Destination_airport + SCHEDULED_DEPARTURE +DAY + O.City + Distance + DAY_OF_WEEK +MONTH + Org_airport_long+ FLIGHT_NUMBER + SCHEDULED_TIME + SCHEDULED_ARRIVAL ,mtry=4,ntree=10,importance=TRUE)
system.time(randomForest(data=tr2, as.factor(Cancelled)~ Destination_airport + SCHEDULED_DEPARTURE +DAY + O.City + Distance + DAY_OF_WEEK +MONTH + Org_airport_long+ FLIGHT_NUMBER + SCHEDULED_TIME + SCHEDULED_ARRIVAL ,mtry=4,ntree=i,importance=TRUE))

# Testing Accuracy 
p2<- predict(flight.efficient, newdata = te2, type = "response")
pred2<- p2 == "YES"
cc<- te2$Cancelled
t1<-table(pred2, cc)
a<- (t1[1,1]+t1[2,2])/sum(t1)
aa<- c(aa,a)
}

plot(1:20, aa)

aa<- as.data.frame(aa)
aa$indi<- 1:20
ggplot(aa, aes(x = indi, y = aa))+
  geom_point()+
  theme_classic()
```


```{r}
df1<- as.data.frame(prop.table(table(flight.training$Cancelled, flight.training$Origin_airport)))
df1<- df1[seq(2,248,2),2:3]
names(df1)<- c("Origin_airport", "Cancellation Rate")
df1<- left_join(df1, airport.info, "Origin_airport")
ggplot(df1, aes(x = Total.Ops, y = `Cancellation Rate` ))+
  geom_point()+
  theme_bw()+
  xlab("")+
  ylab("")+
  theme(plot.title = element_text(hjust = 0.5))+
  ggtitle("Percetage Cancellation vs. Aircraft Movememt")



```






